### ISSUE TITLE
API Cell With No Output Hangs

### ISSUE THREAD

**Issue by Lull3rSkat3r** [jupyter-incubator/kernel_gateway#98]
Code in `notebook-http` mode which has no print or return will hang. For example
```
# POST /example
x = 1 + 1
```

**Comment by dalogsdon** [comment]
Could this be related to https://github.com/jupyter-incubator/dashboards_nodejs_app/issues/56

**Comment by parente** [comment]
Probably not: @Lull3rSkat3r is in `notebook-http` mode here, not the `jupyter-websocket` mode that we're using in dashboards.

**Comment by parente** [comment]
https://github.com/jupyter-incubator/kernel_gateway/blob/master/kernel_gateway/services/notebooks/handlers.py#L43

Looking at the code only, I'm a bit surprised we don't break out here right away.

**Comment by Lull3rSkat3r** [comment]
So doing a little more digging around, I found that the last method was actually returning a value. This caused a execute result to be returned which gave the following error in KG.
```
[E 160217 14:54:06 zmqstream:410] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
        callback(*args, **kwargs)
      File "/opt/conda/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/srv/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 80, in <lambda>
        return lambda msg_list: self._on_reply(kernel_id, msg_list)
      File "/srv/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 74, in _on_reply
        self.on_recv_funcs[kernel_id](msg)
      File "/srv/kernel_gateway/kernel_gateway/services/notebooks/handlers.py", line 46, in on_recv
        result_accumulator['content'] = ''.join(result_accumulator['content'])
    TypeError: sequence item 0: expected str instance, dict found
[E 160217 14:54:06 zmqstream:445] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
        self._handle_recv()
      File "/opt/conda/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/conda/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
        callback(*args, **kwargs)
      File "/opt/conda/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/srv/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 80, in <lambda>
        return lambda msg_list: self._on_reply(kernel_id, msg_list)
      File "/srv/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 74, in _on_reply
        self.on_recv_funcs[kernel_id](msg)
      File "/srv/kernel_gateway/kernel_gateway/services/notebooks/handlers.py", line 46, in on_recv
        result_accumulator['content'] = ''.join(result_accumulator['content'])
    TypeError: sequence item 0: expected str instance, dict found
[E 160217 14:54:06 ioloop:612] Exception in callback None
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.4/site-packages/tornado/ioloop.py", line 866, in start
        handler_func(fd_obj, events)
      File "/opt/conda/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/opt/conda/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 433, in _handle_events
        self._handle_recv()
      File "/opt/conda/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 465, in _handle_recv
        self._run_callback(callback, msg)
      File "/opt/conda/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 407, in _run_callback
        callback(*args, **kwargs)
      File "/opt/conda/lib/python3.4/site-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/srv/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 80, in <lambda>
        return lambda msg_list: self._on_reply(kernel_id, msg_list)
      File "/srv/kernel_gateway/kernel_gateway/services/kernels/pool.py", line 74, in _on_reply
        self.on_recv_funcs[kernel_id](msg)
      File "/srv/kernel_gateway/kernel_gateway/services/notebooks/handlers.py", line 46, in on_recv
        result_accumulator['content'] = ''.join(result_accumulator['content'])
    TypeError: sequence item 0: expected str instance, dict found
```

**Comment by parente** [comment]
We're blindly trying to join both `stream` output strings and `execute_result` dictionaries. Fix is to track both separately and follow the order or output precedence outlined in the README:

1. Errors
2. stdout
3. Execute results

In the case of execution results, just dump the entire list of dictionaries. For streams, continue joining with an empty string separator. For errors, do what we're already doing.

**Comment by Lull3rSkat3r** [comment]
PR #104 has the fix and a test case for this.
