### ISSUE TITLE
Override another use of jinja

### ISSUE THREAD

**Issue by parente** [jupyter-incubator/kernel_gateway#99]
See #71 for how we fixed in the past.

```
kernel_gateway_1 | [KernelGatewayApp] WARNING | Blocking Cross Origin API request.  Origin: http://192.168.99.100:3000, Host: kernel_gateway:8888
kernel_gateway_1 | ERROR:tornado.application:Uncaught exception in write_error
kernel_gateway_1 | Traceback (most recent call last):
kernel_gateway_1 |   File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 1422, in _execute
kernel_gateway_1 |     result = self.prepare()
kernel_gateway_1 |   File "/opt/conda/lib/python3.4/site-packages/kernel_gateway/mixins.py", line 48, in prepare
kernel_gateway_1 |     return super(TokenAuthorizationMixin, self).prepare()
kernel_gateway_1 |   File "/opt/conda/lib/python3.4/site-packages/notebook/base/handlers.py", line 377, in prepare
kernel_gateway_1 |     raise web.HTTPError(404)
kernel_gateway_1 | tornado.web.HTTPError: HTTP 404: Not Found
kernel_gateway_1 |
kernel_gateway_1 | During handling of the above exception, another exception occurred:
kernel_gateway_1 |
kernel_gateway_1 | Traceback (most recent call last):
kernel_gateway_1 |   File "/opt/conda/lib/python3.4/site-packages/tornado/web.py", line 974, in send_error
kernel_gateway_1 |     self.write_error(status_code, **kwargs)
kernel_gateway_1 |   File "/opt/conda/lib/python3.4/site-packages/notebook/base/handlers.py", line 364, in write_error
kernel_gateway_1 |     html = self.render_template('%s.html' % status_code, **ns)
kernel_gateway_1 |   File "/opt/conda/lib/python3.4/site-packages/notebook/base/handlers.py", line 302, in render_template
kernel_gateway_1 |     template = self.get_template(name)
kernel_gateway_1 |   File "/opt/conda/lib/python3.4/site-packages/notebook/base/handlers.py", line 298, in get_template
kernel_gateway_1 |     return self.settings['jinja2_env'].get_template(name)
kernel_gateway_1 | KeyError: 'jinja2_env'
```

**Comment by parente** [comment]
Took a step back and addressed the inconsistency in error reporting among the various handlers. The associated PR should force all error responses to JSON from here on out.
